server:
  port: 8090

spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1111

mybatis:
  mapper-locations: classpath:sql/*.xml
  config-location: classpath:mybatis-config.xml

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api-docs
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace